### ISSUE TITLE
Installation instructions seem incorrect

### ISSUE THREAD

**Issue by drmani** [SimonSchlumbohm/HarmonizR#2]
Using `devtools::install_github("SimonSchlumbohm/HarmonizR")` results in an error:
```
Error: Failed to install "unknown package" from GitHub:
  HTTP error 404.
  Not Found
  Did you spell the repo owner ("SimonSchlumbohm") and repo name ("HarmonizR") correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

```
But it works fine when I use `devtools::install_github("SimonSchlumbohm/HarmonizR/HarmonizR")`

**Comment by SimonSchlumbohm** [comment]
Hello drmani,

thank you for the comment. Yes, you are right. The package itself is a folder within the "HarmonizR" folder. It should already be updated in the SOP.

With best regards

Simon Schlumbohm

**Comment by SimonSchlumbohm** [comment]
If the issue is resolved to your satisfaction, then I would close this Issue-Thread soon.

With best regards

Simon Schlumbohm

**Comment by drmani** [comment]
Hello Simon, 
The issue is resolved. I'll close it.
