### ISSUE TITLE
HarmonizR for single data set

### ISSUE THREAD

**Issue by lisiarend** [SimonSchlumbohm/HarmonizR#7]
Hello,

first of all, thank you very much for providing all the data and also the source code of your package.

I wanted to ask if it is also possible to use HarmonizR for a single data set? Or it is only useful to use it with multiple independent proteomic datasets?

Thank you very much.
Best,
Lis Arend

**Comment by SimonSchlumbohm** [comment]
Hello @lisiarend 

if you have a single dataset with no inherent batch effect in the first place, I'd argue there is nothing to adjust for. I might, however, be severely misinterpreting your question.

HarmonizR was built for NA-tolerant dataset integration, but as long as you witness a batch effect within a dataset you'd like to remove, simply mark the samples accordingly in the description file.
As an example we showed adjustment of TMT datasets in our paper, where we remove biases across plexes.

Best

Simon Schlumbohm

**Comment by lisiarend** [comment]
Actually, I am doing a study on systematically evaluation normalization methods on label-free and TMT data sets. So I havea TMT data set with different TMT-plexes. Therefore before performing proper normalization, we applied different batch effect correction methods. Now I wanted to apply NormalizR for harmonizing the batch effects but was not sure if it works for one specific data set with different batches or if it is only applicable if you have multiple independent TMT data sets.

**Comment by SimonSchlumbohm** [comment]
I believe it should work. I'd suggest just to test it out and compare the results. It wasn't really our focus, though.
